name: 'Publish application'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - name: Checkout
          uses: actions/checkout@v2.3.1

        # Install .NET Core SDK
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v1.5.0
          with:
            dotnet-version: 3.1.x

        - name: Use Node.js
          uses: actions/setup-node@v2.1.1
          
        - name: Install dependencies
          run: npm --prefix ./AssemblyCPU install
          
        - name: css minify
          run: gulp
        
        - name: minify css
          run: gulp --gulpfile AssemblyCPU/gulpfile.js css:prod

        # Run tests
        - name: Test
          run: dotnet test

        # Generate the website
        - name: Publish
          run: dotnet publish AssemblyCPU/AssemblyCPU.csproj --configuration Release

        # Publish the website
        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/master' }} # Publish only when the push is on master
          uses: peaceiris/actions-gh-pages@v3.6.1
          with:
            github_token: ${{ secrets.PUBLISH_TOKEN }}
            publish_branch: gh-pages
            publish_dir: AssemblyCPU/bin/Release/netstandard2.1/publish/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true
